export const QUERY_KEYS = {
  DEV_LOGIN: "devLogin",
  USER: "user",
  USERS: "users",
  ROLES: "roles",
  TOURNAMENT: "tournament",
  TOURNAMENTS: "tournaments",
  APPLICATIONS: "applications",
  PLAYERS: "players",
  PLAYER: "player",
  LOBBIES: "lobbies",
  LOBBY: "lobby",
  LEADERBOARD: "leaderboard",
  LEADERBOARD_ITEM: "leaderboardItem",
} as const;
